language: ruby

before_install:
  - sudo apt-get update
  - sudo apt-get install libgtk-3-dev libgstreamer1.0-dev

script: "xvfb-run bundle exec rake test"

rvm:
  - 2.4
  - 2.5
  - 2.6

branches:
  only:
    - master
